### ISSUE TITLE
SI Stack window not updating correctly

### ISSUE THREAD

**Issue by DyalogRichard** [Dyalog/ride#151]
# RIDE Issue Report

### Describe the issue you are having
The SI Stack window shows \<no stack> when a function is running

### Did you connect to an already running interpreter or start the interpreter from RIDE?
Connected to a running interpreter

### How do you reproduce the issue?
)clear
)copy dfns easter
easter 1996 \<hit ctrl-enter to start tracing>
--- function starts tracing; no stack trace appears
\<hit enter to trace to next line>
--- stack trace appears

### Paste the contents of Help → About (Shift+F1)
IDE:
  Version: 4.0.2784
  Platform: Linux x86_64
  Date: 2017-04-21 13:05:05 +0100
  Git commit: 93dafe26bae19f90d12bd0e7eadd06e33046aa4f
  Preferences:{
    "dbg":"1",
    "wse":"1"
  }

Interpreter:
  Version: 16.0.29800
  Platform: Linux-64
  Edition: Unicode/64
  Date: Apr 24 2017 at 10:28:43

**Comment by flouc001** [comment]
This issue is down to the incoming "ReplyGetStack" protocol message containing invalid JSON. When RIDE tries to parse the JSON string it fails...

![image](https://cloud.githubusercontent.com/assets/11680496/25475689/7f87d0f8-2b2f-11e7-996d-02d3e48db093.png)

The JSON currently looks like this:
`["ReplyGetSIStack",{"stack":[{"description":"#.easter[1]*G←1+19|⍵                ⍝ year "golden number" in 19-year Metonic cycle."}],"tid":0}]`

But should look like this (escaped  double quotes):
`["ReplyGetStack",{"stack":[{"description":"#.easter[1]*G←1+19|⍵                ⍝ year \"golden number\" in 19-year Metonic cycle."}],"tid":0}]`

![image](https://cloud.githubusercontent.com/assets/11680496/25477051/0ee0a780-2b34-11e7-828d-005049707b7a.png)

Above demonstrates that `ij` (invalid JSON that doesn't escape double quotes) breaks the JSON parser.

@johndaintree is this something you could look at from the interpreter side?

**Comment by flouc001** [comment]
http://jsonlint.com/ is a great site for validating JSON.

**Comment by johndaintree** [comment]
Right, I believe I've fixed this. The problem is that I wrote some "by hand" JSON generation to get over some limitations in the API I have to ⎕JSON.

**Comment by jayfoad** [comment]
Fixed in interpreter 16.0.29830.

**Comment by FionaDyalog** [comment]
Still not updating (even when clicking the Refresh icon). Only updates when I actually do something to the broken code.
IDE:
  Version: 4.0.2849
  Platform: Win32
  Date: 2017-07-20 11:23:40 +0100
  Git commit: ff806cb588cd1c8ae908949e27211d64cbf565e9
  Preferences:{
    "dbg":"1",
    "indent":"6",
    "indentComments":"1",
    "indentMethods":"2",
    "kbdLocale":"en_US",
    "lbarOrder":"← +-×÷*⍟⍴⌹○~!? |⌈⌊⍉⊥⊤⊣⊢ =≠≤<>≥≢ ∨∧⍲⍱ ≡↑↓⊂⊃⊆⌷⍋⍒ ⍳⍸∊⍷∪∩ /\\⌿⍀ ,⍪⌽⊖ ¨⍨⍣.∘⍤@ ⍞⎕⍠⌸⌺⌶⍎⍕ ⋄⍝→⍵⍺∇& ¯⍬",
    "zoom":"-1",
    "lineNums":"0"
  }

Interpreter:
  Version: 16.0.30307
  Platform: Windows-64
  Edition: Unicode/64
  Date: Jul  5 2017 at 20:34:46

**Comment by jayfoad** [comment]
@FionaDyalog says it's still broken.

**Comment by e9gille** [comment]
Not sure how to replicate this @FionaDyalog , can you give me a repro?

@johndaintree same problem in ReplyGetThreads:
["ReplyGetThreads",{"threads":[{"description":"Tid:0","state":"Session","tid":0,"flags":"Normal","Treq":"","Location":"0: (Session) #.easter[1] G←1+19|⍵                ⍝ year "golden number" in 19-year Metonic cycle."}]}]
294772 send

**Comment by FionaDyalog** [comment]
Can't replicate it now (not tried a=on a 4.0 build though, only a 4.1).

IDE:
  Version: 4.1.2981
  Platform: Win32
  Date: 2017-11-09 08:45:10 +0100
  Git commit: 38c8b1637bbfddc49b67a00d9e0ba3e866f8f6b5
  Preferences:{
    "dbg":"1"
  }

Interpreter:
  Version: 16.0.31084
  Platform: Windows-64
  Edition: Unicode/64
  Date: Oct  9 2017 at 20:07:20

**Comment by jayfoad** [comment]
> Can't replicate it now

... so I'll close it for now.

**Comment by e9gille** [comment]
@johndaintree ReplyGetThreads has the same issue on the Location property. Need to escape " character.

**Comment by jayfoad** [comment]
> ReplyGetThreads has the same issue on the Location property. Need to escape " character.

Fixed in interpreter 17.0.32895.
